FROM node:18

WORKDIR /app/back

COPY package.json package-lock.json ./
COPY /back/package.json /back/package-lock.json ./back/

RUN npm install

COPY . .

EXPOSE 1337

CMD ["npm", "run", "develop"] 
